variables:
  cachePrefix: 'B'
  buildType: MinSizeRel
  SCCACHE: sccache
  SCCACHE_DIR: $(Agent.BuildDirectory)/sccache
  SCCACHE_IDLE_TIMEOUT: 60

resources:
  repositories:
  - repository: llvm-project
    type: git
    name: llvm/llvm-project
    ref: codelldb/20.x

  - repository: libxml2
    type: github
    name: GNOME/libxml2
    ref:  refs/tags/v2.10.4
    endpoint: github.com_vadimcn

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  container: 'vadimcn/linux-builder:latest'

  strategy:
    matrix:
      x86_64:
        Triple: 'x86_64-linux-gnu'
      arm:
        Triple: 'arm-linux-gnueabihf'
      aarch64:
        Triple: 'aarch64-linux-gnu'

  timeoutInMinutes: 360

  steps:
  - checkout: self
    path: s
    submodules: true
    lfs: true
    fetchDepth: 1

  - checkout: llvm-project
    path: s/llvm-project
    submodules: true
    fetchDepth: 1

  - checkout: libxml2
    path: s/libxml2
    submodules: true
    fetchDepth: 1

  - script: |
      echo "##vso[task.prependpath]$(Build.SourcesDirectory)/arch/linux/bin"
    displayName: Update path

  - task: Cache@2
    inputs:
      key: $(cachePrefix) | $(Agent.OS) | $(Triple) | $(buildType) | $(Build.BuildId)
      restoreKeys: |
        $(cachePrefix) | $(Agent.OS) | $(Triple) | $(buildType)
      path: $(SCCACHE_DIR)
      continueOnError: true
    displayName: SCCache
    condition: always()

  - script: |
      git -C $(Build.SourcesDirectory)/llvm-project remote set-url origin local
      python3 $(Build.SourcesDirectory)/lldb_build.py \
        --build-dir=$(Agent.BuildDirectory) \
        --sysroot=/stretch \
        --ccache=$(SCCACHE) \
        --target=$(Triple) \
        --build-type=$(buildType) \
        --release-package
    displayName: 'Build'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Agent.BuildDirectory)'
      contents: '*.zip'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'lldb--$(Triple)'

  - script: |
      cd $(Agent.BuildDirectory)
      cat /proc/cpuinfo > system.log
      cat /proc/meminfo >> system.log
      env > env.log
      find $(Agent.BuildDirectory) -type d > build-tree.log
      zip --recurse-patterns $(Agent.BuildDirectory)/$(Triple).zip "*.log" "CMakeCache.txt"
      echo "##vso[artifact.upload artifactname=logs]$(Agent.BuildDirectory)/$(Triple).zip"
    displayName: 'Logs'
    condition: always()    

############################################################

- job: OSX
  strategy:
    matrix:
      x86_64:
        DeploymentTarget: '10.12'
        Triple: 'x86_64-apple-darwin'
      aarch64:
        DeploymentTarget: '11.0'
        Triple: 'aarch64-apple-darwin'

  timeoutInMinutes: 360

  pool:
    vmImage: 'macOS-latest'

  steps:
  - checkout: self
    path: s
    submodules: true
    lfs: true    
    fetchDepth: 1

  - checkout: llvm-project
    path: s/llvm-project
    submodules: true
    fetchDepth: 1

  - checkout: libxml2
    path: s/libxml2
    submodules: true
    fetchDepth: 1

  - script: |
      echo "##vso[task.prependpath]$(Build.SourcesDirectory)/arch/darwin/bin"
    displayName: Update path    

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
      architecture: 'x64'

  - script: |
      brew install pcre automake ninja pkg-config swig
    displayName: 'Install tools'

  - task: Cache@2
    inputs:
      key: $(cachePrefix) | $(Agent.OS) | $(Triple) | $(buildType) | $(Build.BuildId)
      restoreKeys: |
        $(cachePrefix) | $(Agent.OS) | $(Triple) | $(buildType)
      path: $(SCCACHE_DIR)
      continueOnError: true
    displayName: SCCache
    condition: always()

  - script: |
      mkdir -p $(Agent.BuildDirectory)/llvm/bin
      cp /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver $(Agent.BuildDirectory)/llvm/bin/debugserver
    displayName: 'PreBuild'

  - script: |
      git -C $(Build.SourcesDirectory)/llvm-project remote set-url origin local
      export MACOSX_DEPLOYMENT_TARGET=$(DeploymentTarget)
      xcrun -sdk macosx python3 $(Build.SourcesDirectory)/lldb_build.py \
        --build-dir=$(Agent.BuildDirectory) \
        --ccache=$(SCCACHE) \
        --target=$(Triple) \
        --build-type=$(buildType) \
        --release-package
    displayName: 'Build'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Agent.BuildDirectory)'
      contents: '*.zip'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
 
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'lldb--$(Triple)'

  - script: |
      cd $(Agent.BuildDirectory)
      sysctl -a > system.log
      env > env.log
      find $(Agent.BuildDirectory) -type d > build-tree.log
      xcversion selected > xcversion-selected.log
      xcversion list > xcversion-list.log
      xcodebuild -showsdks > xcodebuild-sdks.log
      zip --recurse-patterns $(Agent.BuildDirectory)/$(Triple).zip "*.log" "CMakeCache.txt"
      echo "##vso[artifact.upload artifactname=logs]$(Agent.BuildDirectory)/$(Triple).zip"
    displayName: 'Logs'
    condition: always()

############################################################

- job: Windows
  pool:
    vmImage: 'windows-2019'

  variables:
    Triple: 'x86_64-windows-msvc'
    
  timeoutInMinutes: 360

  steps:
  - checkout: self
    path: s
    submodules: true
    lfs: true    
    fetchDepth: 1

  - checkout: llvm-project
    path: s/llvm-project
    submodules: true
    fetchDepth: 1

  - checkout: libxml2
    path: s/libxml2
    submodules: true
    fetchDepth: 1

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
      architecture: 'x64'

  - task: BatchScript@1
    inputs:
      filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
      arguments: -arch=amd64 -host_arch=amd64
      modifyEnvironment: true
    displayName: VsDevCmd

  - script: |
      C:\msys64\usr\bin\pacman --noconfirm -S automake autoconf
      C:\msys64\usr\bin\pacman --noconfirm -S pcre-devel bison sed
      echo ##vso[task.prependpath]$(Build.SourcesDirectory)/arch/windows/bin
      echo ##vso[task.prependpath]C:\msys64\usr\bin
      echo ##vso[task.setvariable variable=CPATH]C:\msys64\usr\include
      echo ##vso[task.setvariable variable=LIBRARY_PATH]C:\msys64\usr\lib
    displayName: 'Install tools'

  - task: Cache@2
    inputs:
      key: $(cachePrefix) | $(Agent.OS) | $(Triple) | $(buildType) | $(Build.BuildId)
      restoreKeys: |
        $(cachePrefix) | $(Agent.OS) | $(Triple) | $(buildType)
      path: $(SCCACHE_DIR)
      continueOnError: true
    displayName: SCCache
    condition: always()

  - script: |
      mkdir -p $(Agent.BuildDirectory)\llvm\bin
      copy "$(VCToolsRedistDir)\x64\Microsoft.VC142.CRT\vcruntime140_1.dll" "$(Agent.BuildDirectory)\llvm\bin"
      git -C $(Build.SourcesDirectory)/llvm-project remote set-url origin local
      $(USEPYTHONVERSION_PYTHONLOCATION)\python3 $(Build.SourcesDirectory)/lldb_build.py ^
        --build-dir=$(Agent.BuildDirectory) ^
        --ccache=$(SCCACHE) ^
        --target=$(Triple) ^
        --build-type=$(buildType) ^
        --release-package 
    displayName: 'Build'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Agent.BuildDirectory)'
      contents: '*.zip'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'lldb--$(Triple)'

  - script: |
      cd $(Agent.BuildDirectory)
      set > env.log
      tree /a > build-tree.log
      dir $(Agent.BuildDirectory)\llvm\bin $(Agent.BuildDirectory)\llvm\lib > build-bin.log
      zip --recurse-patterns $(Agent.BuildDirectory)\$(Triple).zip "*.log" "CMakeCache.txt"
      echo ##vso[artifact.upload artifactname=logs]$(Agent.BuildDirectory)\$(Triple).zip
    displayName: 'Logs'
    condition: always()
